# Generated by Django 5.2.5 on 2025-08-26 17:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Caja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(auto_now_add=True)),
                ('monto_inicial', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('monto_final', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('total_vendido', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('cerrada', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Mesa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField(unique=True)),
                ('ocupada', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Plato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=6)),
                ('categoria', models.CharField(default='Comida', max_length=50)),
                ('activo', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('cerrado', models.BooleanField(default=False)),
                ('mesa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ventas.mesa')),
            ],
        ),
        migrations.CreateModel(
            name='DetallePedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField(default=1)),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ventas.pedido')),
                ('plato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ventas.plato')),
            ],
        ),
    ]
