# Generated by Django 5.2.5 on 2025-08-26 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='plato',
            options={'ordering': ['categoria', 'nombre']},
        ),
        migrations.AlterField(
            model_name='plato',
            name='categoria',
            field=models.CharField(db_index=True, default='Otros', max_length=50),
        ),
        migrations.AlterField(
            model_name='plato',
            name='precio',
            field=models.DecimalField(decimal_places=2, max_digits=7),
        ),
        migrations.AlterUniqueTogether(
            name='plato',
            unique_together={('nombre', 'categoria')},
        ),
    ]
