# Generated by Django 5.2.5 on 2025-08-27 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0002_alter_plato_options_alter_plato_categoria_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='detallepedido',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('enviado', 'Enviado')], default='pendiente', max_length=20),
        ),
    ]
