# Generated by Django 5.2.5 on 2025-08-27 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0003_detallepedido_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detallepedido',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('servido', 'Servido')], default='pendiente', max_length=20),
        ),
    ]
