# Generated by Django 5.2.5 on 2025-09-06 17:25

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0004_alter_detallepedido_estado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='caja',
            name='cerrada',
        ),
        migrations.RemoveField(
            model_name='caja',
            name='fecha',
        ),
        migrations.RemoveField(
            model_name='caja',
            name='total_vendido',
        ),
        migrations.AddField(
            model_name='caja',
            name='abierta',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='caja',
            name='fecha_apertura',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='caja',
            name='fecha_cierre',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='caja',
            name='monto_final',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='caja',
            name='monto_inicial',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
