# Generated by Django 5.2.5 on 2025-09-06 17:47

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0005_remove_caja_cerrada_remove_caja_fecha_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='caja',
            name='abierta',
        ),
        migrations.AddField(
            model_name='caja',
            name='cerrada',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='caja',
            name='total_vendido',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
        migrations.AlterField(
            model_name='caja',
            name='fecha_apertura',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='caja',
            name='monto_final',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='caja',
            name='monto_inicial',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
