# Generated by Django 5.2.5 on 2025-09-06 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0006_remove_caja_abierta_caja_cerrada_caja_total_vendido_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='caja',
            name='abierta',
            field=models.BooleanField(default=True),
        ),
    ]
