# Generated by Django 5.2.5 on 2025-09-06 19:07

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0007_caja_abierta'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='caja',
            name='cerrada',
        ),
        migrations.RemoveField(
            model_name='mesa',
            name='ocupada',
        ),
        migrations.AddField(
            model_name='caja',
            name='fecha',
            field=models.DateField(blank=True, default=django.utils.timezone.localdate, null=True),
        ),
        migrations.AlterField(
            model_name='mesa',
            name='numero',
            field=models.PositiveIntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='plato',
            name='precio',
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
    ]
