# Generated by Django 5.2.5 on 2025-09-06 19:18

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0008_remove_caja_cerrada_remove_mesa_ocupada_caja_fecha_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caja',
            name='fecha',
            field=models.DateField(default=django.utils.timezone.localdate, unique=True),
        ),
    ]
