# Generated by Django 5.2.5 on 2025-09-13 06:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0009_alter_caja_fecha'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='caja',
            options={'ordering': ['-fecha']},
        ),
        migrations.AlterModelOptions(
            name='mesa',
            options={'ordering': ['numero']},
        ),
        migrations.AlterModelOptions(
            name='pedido',
            options={'ordering': ['-creado']},
        ),
        migrations.AlterField(
            model_name='detallepedido',
            name='pedido',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='ventas.pedido'),
        ),
    ]
