# Generated by Django 5.2.5 on 2025-09-16 04:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0010_alter_caja_options_alter_mesa_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedido',
            name='cerrado',
        ),
        migrations.AddField(
            model_name='mesa',
            name='es_para_llevar',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='pedido',
            name='estado',
            field=models.CharField(choices=[('abierto', 'Abierto'), ('cerrado', 'Cerrado'), ('cancelado', 'Cancelado')], default='abierto', max_length=10),
        ),
        migrations.AddField(
            model_name='pedido',
            name='para_llevar',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='mesa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ventas.mesa'),
        ),
    ]
